import { useEffect, useState } from 'react'
import { X } from 'lucide-react'
import type { MailAccountData, MailProvider } from '../../../lib/mailHubMockData'
import {
  DEFAULT_WEBMAIL_URL,
  MAX_MAIL_ACCOUNT_LABEL_LENGTH,
  PROVIDER_EMAIL_DOMAIN,
  createMailAccount,
  emailInputForProviderChange,
  emailToFormInput,
  extractEmailLocalPart,
  generateMailAccountLabel,
  isAutoGeneratedLabel,
  isValidMailAccountLabel,
  resolveMailAccountEmail,
  updateMailAccount,
  usesLocalPartEmailInput,
  type NewMailAccountInput,
  type UpdateMailAccountInput,
} from '../../../lib/mailHubStorage'

type MailAccountModalProps = {
  open: boolean
  mode: 'add' | 'edit'
  account?: MailAccountData
  onClose: () => void
  onSave: (account: MailAccountData) => void
}

const PROVIDER_OPTIONS: { id: MailProvider; label: string }[] = [
  { id: 'gmail', label: 'Gmail' },
  { id: 'naver', label: 'Naver' },
  { id: 'company', label: 'Company Mail' },
  { id: 'custom', label: 'Custom' },
]

type FormState = {
  label: string
  provider: MailProvider
  email: string
  webmailUrl: string
}

const EMPTY_ADD_FORM: FormState = {
  label: generateMailAccountLabel('gmail'),
  provider: 'gmail',
  email: '',
  webmailUrl: DEFAULT_WEBMAIL_URL.gmail ?? '',
}

const FULL_EMAIL_PLACEHOLDER: Partial<Record<MailProvider, string>> = {
  company: 'employee@company.com',
  custom: 'example@domain.com',
}

function parseLocalPartInput(provider: MailProvider, value: string): { localPart: string; error: string | null } {
  const domain = PROVIDER_EMAIL_DOMAIN[provider]
  if (!domain) return { localPart: value, error: null }

  if (!value.includes('@')) {
    return { localPart: value, error: null }
  }

  const lower = value.toLowerCase()
  if (lower.endsWith(`@${domain}`)) {
    return { localPart: value.slice(0, -(domain.length + 1)), error: null }
  }

  return {
    localPart: extractEmailLocalPart(value),
    error:
      provider === 'gmail'
        ? 'Gmail 계정은 @gmail.com 주소만 사용할 수 있습니다.'
        : 'Naver 계정은 @naver.com 주소만 사용할 수 있습니다.',
  }
}

function formFromAccount(account: MailAccountData): FormState {
  return {
    label: account.label,
    provider: account.provider,
    email: emailToFormInput(account.provider, account.email),
    webmailUrl: account.webmailUrl ?? DEFAULT_WEBMAIL_URL[account.provider] ?? '',
  }
}

export default function AddMailAccountModal({
  open,
  mode,
  account,
  onClose,
  onSave,
}: MailAccountModalProps) {
  const isEdit = mode === 'edit'
  const [form, setForm] = useState<FormState>(EMPTY_ADD_FORM)
  const [emailError, setEmailError] = useState<string | null>(null)
  const [labelCustomized, setLabelCustomized] = useState(false)
  const [labelTouched, setLabelTouched] = useState(false)

  useEffect(() => {
    if (!open) return

    if (isEdit && account) {
      setForm(formFromAccount(account))
      setLabelCustomized(!isAutoGeneratedLabel(account.provider, account.email, account.label))
    } else {
      setForm({ ...EMPTY_ADD_FORM })
      setLabelCustomized(false)
    }
    setLabelTouched(false)
    setEmailError(null)

    function handleKeyDown(event: KeyboardEvent) {
      if (event.key === 'Escape') onClose()
    }

    document.addEventListener('keydown', handleKeyDown)
    document.body.style.overflow = 'hidden'

    return () => {
      document.removeEventListener('keydown', handleKeyDown)
      document.body.style.overflow = ''
    }
  }, [open, onClose, isEdit, account])

  if (!open) return null

  const resolvedEmail = resolveMailAccountEmail(form.provider, form.email)
  const labelValid = isValidMailAccountLabel(form.label)
  const canSave = resolvedEmail.valid && !emailError && labelValid

  function maybeAutoUpdateLabel(
    provider: MailProvider,
    emailInput: string,
    customized: boolean,
  ): string | undefined {
    if (customized) return undefined
    const resolved = resolveMailAccountEmail(provider, emailInput)
    if (resolved.valid) return generateMailAccountLabel(provider, resolved.email)
    return generateMailAccountLabel(provider)
  }

  function handleProviderChange(provider: MailProvider) {
    const defaultUrl = DEFAULT_WEBMAIL_URL[provider] ?? ''
    setForm((current) => {
      const nextEmail = emailInputForProviderChange(current.provider, provider, current.email)
      const nextLabel = maybeAutoUpdateLabel(provider, nextEmail, labelCustomized)
      return {
        ...current,
        provider,
        email: nextEmail,
        webmailUrl: defaultUrl,
        ...(nextLabel !== undefined ? { label: nextLabel } : {}),
      }
    })
    setEmailError(null)
  }

  function handleLabelChange(value: string) {
    setLabelTouched(true)
    setLabelCustomized(true)
    setForm((current) => ({ ...current, label: value.slice(0, MAX_MAIL_ACCOUNT_LABEL_LENGTH) }))
  }

  function handleEmailChange(value: string) {
    if (usesLocalPartEmailInput(form.provider)) {
      const { localPart, error } = parseLocalPartInput(form.provider, value)
      setForm((current) => {
        const nextLabel = maybeAutoUpdateLabel(current.provider, localPart, labelCustomized)
        return {
          ...current,
          email: localPart,
          ...(nextLabel !== undefined ? { label: nextLabel } : {}),
        }
      })
      setEmailError(error)
      return
    }

    setForm((current) => {
      const nextLabel = maybeAutoUpdateLabel(current.provider, value, labelCustomized)
      return {
        ...current,
        email: value,
        ...(nextLabel !== undefined ? { label: nextLabel } : {}),
      }
    })
    setEmailError(null)
  }

  function handleSave() {
    setLabelTouched(true)
    if (!canSave || !resolvedEmail.valid) return

    if (isEdit && account) {
      const input: UpdateMailAccountInput = {
        provider: form.provider,
        label: form.label.trim(),
        email: resolvedEmail.email,
        webmailUrl: form.webmailUrl.trim() || undefined,
      }
      const updated = updateMailAccount([account], account.id, input)[0]
      if (updated) onSave(updated)
    } else {
      const input: NewMailAccountInput = {
        provider: form.provider,
        label: form.label.trim(),
        email: resolvedEmail.email,
        webmailUrl: form.webmailUrl.trim() || undefined,
      }
      onSave(createMailAccount(input))
    }

    onClose()
  }

  const usesLocalPart = usesLocalPartEmailInput(form.provider)
  const providerDomain = PROVIDER_EMAIL_DOMAIN[form.provider]
  const displayEmailError =
    emailError ?? (resolvedEmail.valid ? null : form.email.trim() ? resolvedEmail.error : null)
  const displayLabelError =
    labelTouched && form.label.trim() && !isValidMailAccountLabel(form.label)
      ? `메일 이름은 ${MAX_MAIL_ACCOUNT_LABEL_LENGTH}자 이내로 입력해주세요.`
      : labelTouched && !form.label.trim()
        ? '메일 이름을 입력해주세요.'
        : null

  const titleId = isEdit ? 'edit-mail-account-title' : 'add-mail-account-title'

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      <button
        type="button"
        aria-label="모달 닫기"
        className="absolute inset-0 bg-slate-900/40 backdrop-blur-[1px]"
        onClick={onClose}
      />

      <div
        role="dialog"
        aria-modal="true"
        aria-labelledby={titleId}
        className="relative max-h-[90vh] w-full max-w-md overflow-y-auto rounded-modal border border-line bg-surface p-6 shadow-pop"
      >
        <button
          type="button"
          onClick={onClose}
          aria-label="닫기"
          className="absolute right-4 top-4 rounded-md p-1 text-slate-400 transition-colors hover:bg-canvas hover:text-slate-600"
        >
          <X size={18} strokeWidth={1.75} />
        </button>

        <h2 id={titleId} className="text-lg font-semibold tracking-tight text-slate-900">
          {isEdit ? '메일 계정 수정' : '메일 계정 추가'}
        </h2>
        <p className="mt-1 text-sm text-slate-500">
          {isEdit ? '계정 정보를 수정하세요.' : '계정 정보를 입력해 Mail Hub에 추가하세요.'}
        </p>

        <div className="mt-4 space-y-3">
          <label className="block">
            <span className="mb-1 block text-xs font-medium text-slate-600">메일 이름</span>
            <input
              type="text"
              name="mailAccountLabel"
              value={form.label}
              onChange={(event) => handleLabelChange(event.target.value)}
              placeholder="예: 개인 Gmail, 회사 메일, 네이버 메일"
              maxLength={MAX_MAIL_ACCOUNT_LABEL_LENGTH}
              autoComplete="off"
              className={
                'h-9 w-full rounded-btn border bg-canvas/50 px-3 text-sm text-slate-700 placeholder:text-slate-400 focus:outline-none focus:ring-2 ' +
                (displayLabelError
                  ? 'border-danger/40 focus:border-danger/40 focus:ring-danger/10'
                  : 'border-line/70 focus:border-brand/30 focus:ring-brand/10')
              }
            />
            {displayLabelError ? (
              <p className="mt-1 text-xs text-danger">{displayLabelError}</p>
            ) : null}
          </label>

          <label className="block">
            <span className="mb-1 block text-xs font-medium text-slate-600">메일 서비스</span>
            <select
              value={form.provider}
              onChange={(event) => handleProviderChange(event.target.value as MailProvider)}
              className="h-9 w-full rounded-btn border border-line/70 bg-canvas/50 px-3 text-sm text-slate-700 focus:border-brand/30 focus:outline-none focus:ring-2 focus:ring-brand/10"
            >
              {PROVIDER_OPTIONS.map((option) => (
                <option key={option.id} value={option.id}>
                  {option.label}
                </option>
              ))}
            </select>
          </label>

          <label className="block">
            <span className="mb-1 block text-xs font-medium text-slate-600">이메일 주소</span>
            {usesLocalPart && providerDomain ? (
              <div
                className={
                  'flex h-9 items-center overflow-hidden rounded-btn border bg-canvas/50 ' +
                  (displayEmailError
                    ? 'border-danger/40 focus-within:border-danger/40 focus-within:ring-2 focus-within:ring-danger/10'
                    : 'border-line/70 focus-within:border-brand/30 focus-within:ring-2 focus-within:ring-brand/10')
                }
              >
                <input
                  type="text"
                  value={form.email}
                  onChange={(event) => handleEmailChange(event.target.value)}
                  placeholder="example"
                  autoComplete="username"
                  className="min-w-0 flex-1 bg-transparent px-3 text-sm text-slate-700 placeholder:text-slate-400 focus:outline-none"
                />
                <span className="shrink-0 pr-3 text-sm text-slate-400">@{providerDomain}</span>
              </div>
            ) : (
              <input
                type="email"
                value={form.email}
                onChange={(event) => handleEmailChange(event.target.value)}
                placeholder={FULL_EMAIL_PLACEHOLDER[form.provider] ?? 'example@domain.com'}
                className={
                  'h-9 w-full rounded-btn border bg-canvas/50 px-3 text-sm text-slate-700 placeholder:text-slate-400 focus:outline-none focus:ring-2 ' +
                  (displayEmailError
                    ? 'border-danger/40 focus:border-danger/40 focus:ring-danger/10'
                    : 'border-line/70 focus:border-brand/30 focus:ring-brand/10')
                }
              />
            )}
            {displayEmailError ? (
              <p className="mt-1 text-xs text-danger">{displayEmailError}</p>
            ) : null}
          </label>

          <label className="block">
            <span className="mb-1 block text-xs font-medium text-slate-600">웹메일 주소</span>
            <input
              type="url"
              value={form.webmailUrl}
              onChange={(event) =>
                setForm((current) => ({ ...current, webmailUrl: event.target.value }))
              }
              placeholder="https://mail.google.com/mail/"
              className="h-9 w-full rounded-btn border border-line/70 bg-canvas/50 px-3 text-sm text-slate-700 placeholder:text-slate-400 focus:border-brand/30 focus:outline-none focus:ring-2 focus:ring-brand/10"
            />
          </label>
        </div>

        <div className="mt-5 flex items-center justify-end gap-2">
          <button
            type="button"
            onClick={onClose}
            className="rounded-btn border border-line bg-surface px-4 py-2 text-sm font-medium text-slate-600 transition-colors hover:bg-canvas"
          >
            취소
          </button>
          <button
            type="button"
            disabled={!canSave}
            onClick={handleSave}
            className={
              'rounded-btn px-4 py-2 text-sm font-medium text-white transition-colors ' +
              (canSave ? 'bg-brand hover:bg-brand-hover' : 'cursor-not-allowed bg-brand/40')
            }
          >
            {isEdit ? '수정 완료' : '저장'}
          </button>
        </div>
      </div>
    </div>
  )
}
